<?php

use Illuminate\Database\Seeder;

class TaxesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $table = 'taxes';

        DB::table($table)->truncate();

        DB::table($table)->insert([
            0 => [
                'id' => 1,
                'country_id' => 160,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 20,
            ],
            1 => [
                'id' => 2,
                'country_id' => 145,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 6,
            ],
            2 => [
                'id' => 3,
                'country_id' => 161,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 10,
            ],
            3 => [
                'id' => 4,
                'country_id' => 142,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 25,
            ],
            4 => [
                'id' => 5,
                'country_id' => 146,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 19,
            ],
            5 => [
                'id' => 6,
                'country_id' => 136,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 21,
            ],
            6 => [
                'id' => 7,
                'country_id' => 147,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 25,
            ],
            7 => [
                'id' => 8,
                'country_id' => 130,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 20,
            ],
            8 => [
                'id' => 9,
                'country_id' => 162,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 24,
            ],
            9 => [
                'id' => 10,
                'country_id' => 150,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 20,
            ],
            10 => [
                'id' => 11,
                'country_id' => 149,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 6,
            ],
            11 => [
                'id' => 12,
                'country_id' => 143,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 24,
            ],
            12 => [
                'id' => 13,
                'country_id' => 144,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 23,
            ],
            13 => [
                'id' => 14,
                'country_id' => 121,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 27,
            ],
            14 => [
                'id' => 15,
                'country_id' => 151,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 23,
            ],
            15 => [
                'id' => 16,
                'country_id' => 131,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 21,
            ],
            16 => [
                'id' => 17,
                'country_id' => 132,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 21,
            ],
            17 => [
                'id' => 18,
                'country_id' => 152,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 17,
            ],
            18 => [
                'id' => 19,
                'country_id' => 123,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 18,
            ],
            19 => [
                'id' => 20,
                'country_id' => 141,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 21,
            ],
            20 => [
                'id' => 21,
                'country_id' => 154,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 23,
            ],
            21 => [
                'id' => 22,
                'country_id' => 153,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 23,
            ],
            22 => [
                'id' => 23,
                'country_id' => 126,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 19,
            ],
            23 => [
                'id' => 24,
                'country_id' => 135,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 20,
            ],
            24 => [
                'id' => 25,
                'country_id' => 136,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 22,
            ],
            25 => [
                'id' => 26,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 0,
            ],
            26 => [
                'id' => 27,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => 2307,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 0,
            ],
            27 => [
                'id' => 28,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => 2323,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 0,
            ],
            28 => [
                'id' => 29,
                'country_id' => 128,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 25,
            ],
            29 => [
                'id' => 30,
                'country_id' => 148,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 20,
            ],
            30 => [
                'id' => 31,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 0,
            ],
            31 => [
                'id' => 32,
                'country_id' => 85,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 15,
            ],
            32 => [
                'id' => 33,
                'country_id' => 160,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            33 => [
                'id' => 34,
                'country_id' => 145,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            34 => [
                'id' => 35,
                'country_id' => 161,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            35 => [
                'id' => 36,
                'country_id' => 142,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            36 => [
                'id' => 37,
                'country_id' => 146,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            37 => [
                'id' => 38,
                'country_id' => 136,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            38 => [
                'id' => 39,
                'country_id' => 147,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            39 => [
                'id' => 40,
                'country_id' => 130,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            40 => [
                'id' => 41,
                'country_id' => 162,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            41 => [
                'id' => 42,
                'country_id' => 150,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            42 => [
                'id' => 43,
                'country_id' => 149,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            43 => [
                'id' => 44,
                'country_id' => 143,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            44 => [
                'id' => 45,
                'country_id' => 121,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            45 => [
                'id' => 46,
                'country_id' => 144,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            46 => [
                'id' => 47,
                'country_id' => 144,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            47 => [
                'id' => 48,
                'country_id' => 131,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            48 => [
                'id' => 49,
                'country_id' => 132,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            49 => [
                'id' => 50,
                'country_id' => 152,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            50 => [
                'id' => 51,
                'country_id' => 123,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            51 => [
                'id' => 52,
                'country_id' => 141,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            52 => [
                'id' => 53,
                'country_id' => 154,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            53 => [
                'id' => 54,
                'country_id' => 153,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            54 => [
                'id' => 55,
                'country_id' => 126,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            55 => [
                'id' => 56,
                'country_id' => 135,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            56 => [
                'id' => 57,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            57 => [
                'id' => 58,
                'country_id' => 128,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            58 => [
                'id' => 59,
                'country_id' => 148,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'zrate',
                'type' => 'none',
                'amount' => 0,
            ],
            59 => [
                'id' => 60,
                'country_id' => 160,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            60 => [
                'id' => 61,
                'country_id' => 161,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            61 => [
                'id' => 62,
                'country_id' => 145,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            62 => [
                'id' => 63,
                'country_id' => 142,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            63 => [
                'id' => 64,
                'country_id' => 146,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            64 => [
                'id' => 65,
                'country_id' => 136,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            65 => [
                'id' => 66,
                'country_id' => 147,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            66 => [
                'id' => 67,
                'country_id' => 130,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            67 => [
                'id' => 68,
                'country_id' => 162,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            68 => [
                'id' => 69,
                'country_id' => 150,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            69 => [
                'id' => 70,
                'country_id' => 149,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            70 => [
                'id' => 71,
                'country_id' => 143,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            71 => [
                'id' => 72,
                'country_id' => 121,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            72 => [
                'id' => 73,
                'country_id' => 144,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            73 => [
                'id' => 74,
                'country_id' => 151,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            74 => [
                'id' => 75,
                'country_id' => 131,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            75 => [
                'id' => 76,
                'country_id' => 132,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            76 => [
                'id' => 77,
                'country_id' => 152,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            77 => [
                'id' => 78,
                'country_id' => 123,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            78 => [
                'id' => 79,
                'country_id' => 141,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            79 => [
                'id' => 80,
                'country_id' => 154,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            80 => [
                'id' => 81,
                'country_id' => 153,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            81 => [
                'id' => 82,
                'country_id' => 126,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            82 => [
                'id' => 83,
                'country_id' => 137,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            83 => [
                'id' => 84,
                'country_id' => 135,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            84 => [
                'id' => 85,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            85 => [
                'id' => 86,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            86 => [
                'id' => 87,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            87 => [
                'id' => 88,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => 2307,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            88 => [
                'id' => 89,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => 2323,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            89 => [
                'id' => 90,
                'country_id' => 128,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            90 => [
                'id' => 91,
                'country_id' => 148,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            91 => [
                'id' => 92,
                'country_id' => 85,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'video',
                'type' => 'standard',
                'amount' => 18,
            ],
            92 => [
                'id' => 93,
                'country_id' => 147,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 25,
            ],
            93 => [
                'id' => 94,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => 2307,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 4,
            ],
            94 => [
                'id' => 95,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => 2323,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 4,
            ],
            95 => [
                'id' => 96,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 4,
            ],
            96 => [
                'id' => 97,
                'country_id' => 149,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 0,
            ],
            97 => [
                'id' => 98,
                'country_id' => 150,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 5.5,
            ],
            98 => [
                'id' => 99,
                'country_id' => 161,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 0,
            ],
            99 => [
                'id' => 100,
                'country_id' => 142,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 5,
            ],
            100 => [
                'id' => 101,
                'country_id' => 144,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 5,
            ],
            101 => [
                'id' => 102,
                'country_id' => 123,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 5,
            ],
            102 => [
                'id' => 103,
                'country_id' => 125,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 5,
            ],
            103 => [
                'id' => 104,
                'country_id' => 154,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 6,
            ],
            104 => [
                'id' => 105,
                'country_id' => 128,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 6,
            ],
            105 => [
                'id' => 106,
                'country_id' => 160,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 10,
            ],
            106 => [
                'id' => 107,
                'country_id' => 130,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 10,
            ],
            107 => [
                'id' => 108,
                'country_id' => 149,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 7,
            ],
            108 => [
                'id' => 109,
                'country_id' => 143,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 0,
            ],
            109 => [
                'id' => 110,
                'country_id' => 121,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 0,
            ],
            110 => [
                'id' => 111,
                'country_id' => 131,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 0,
            ],
            111 => [
                'id' => 112,
                'country_id' => 132,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 0,
            ],
            112 => [
                'id' => 113,
                'country_id' => 141,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 9,
            ],
            113 => [
                'id' => 114,
                'country_id' => 126,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 1.0,
            ],
            114 => [
                'id' => 115,
                'country_id' => 137,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 0,
            ],
            115 => [
                'id' => 116,
                'country_id' => 135,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 0,
            ],
            116 => [
                'id' => 117,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 4,
            ],
            117 => [
                'id' => 118,
                'country_id' => 155,
                'state_id' => null,
                'city_id' => 2307,
                'cat_type' => 'ebook',
                'type' => 'standard',
                'amount' => 4,
            ],
            118 => [
                'id' => 119,
                'country_id' => 151,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 4,
            ],
            119 => [
                'id' => 120,
                'country_id' => 85,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 5,
            ],
            120 => [
                'id' => 121,
                'country_id' => 152,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 10,
            ],
            121 => [
                'id' => 122,
                'country_id' => 146,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 3,
            ],
            122 => [
                'id' => 123,
                'country_id' => 136,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 6,
            ],
            123 => [
                'id' => 124,
                'country_id' => 145,
                'state_id' => null,
                'city_id' => null,
                'cat_type' => 'vat',
                'type' => 'standard',
                'amount' => 0,
            ],
        ]);
    }
}
